[[ftable_AbstractRxN]]
=== AbstractRxN

[cols="a,a,a,a,a,a,a,a",options="headers,unnumbered"]
|===
8+| [underline]#IHO Definition:# An abstract superclass for information types that encode rules, recommendations, and general information in text or graphic form.
8+h| [underline]#S-127 Information Type:# AbstractRxN (Abstract type)
8+h| [underline]#Super Type:# InformationType
3+h| S-127 Attribute h| S-57 Acronym 2+h| Allowable Encoding Value h| Type h| Multiplicity
            
3+| Category of Authority |
2+|2: Border Control +
3: Police +
4: Port +
5: Immigration +
6: Health +
7: Coast Guard +
8: Agricultural +
9: Military +
10: Private Company +
11: Maritime Police +
12: Environmental +
13: Fishery +
14: Finance +
15: Maritime +
16: Customs +
 |EN | 0,1

3+| RxN Code | 2+| |  C | 0,*
3+| &nbsp;&nbsp;&nbsp;&nbsp;Category of RxN |
2+|1: Navigation +
2: Communication +
3: Environmental Protection +
4: Wildlife Protection +
5: Security +
6: Customs +
7: Cargo Operation +
8: Refuge +
9: Health +
10: Natural Resources or Exploitation +
11: Port +
12: Finance +
13: Agriculture +
 |(S) CL | 0,1

3+| &nbsp;&nbsp;&nbsp;&nbsp;Action or Activity |
2+|1: Navigating With a Pilot +
2: Entering Port +
3: Leaving Port +
4: Berthing +
5: Slipping +
6: Anchoring +
7: Weighing Anchor +
8: Transiting +
9: Overtaking +
10: Reporting +
11: Working Cargo +
12: Landing +
13: Diving +
14: Fishing +
15: Discharging Overboard +
16: Passing +
17: Ballast Water Exchange +
18: Hull Cleaning +
19: Scientific Research +
20: Tourism +
21: Education +
22: Infrastructure Maintenance +
 |(S) CL | 0,1

3+| &nbsp;&nbsp;&nbsp;&nbsp;Headline |
2+| |(S) TE | 0,* (ordered)

3+| Text Content | 2+| |  C | 0,*
3+| &nbsp;&nbsp;&nbsp;&nbsp;Category of Text |
2+|1: Abstract or Summary +
2: Extract +
3: Full Text +
 |(S) EN | 0,1

3+| &nbsp;&nbsp;&nbsp;&nbsp;Information | 2+| | (S)  C | 0,*
3+| &nbsp;&nbsp;&nbsp;&nbsp;Online Resource | 2+| | (S)  C | 0,1
3+| &nbsp;&nbsp;&nbsp;&nbsp;Source Indication | 2+| | (S)  C | 0,*
8+h| Inherited Attributes

3+h| S-127 Attribute 3+h| Inherited From h| Type h| Multiplicity
            
3+| Feature Name 3+| InformationType | C | 0,*
3+| Fixed Date Range 3+| InformationType | C | 0,1
3+| Periodic Date Range 3+| InformationType | C | 0,*
3+| Graphic 3+| InformationType | C | 0,*
3+| Source Indication 3+| InformationType | C | 0,*
|===

[cols="a,a,a,a,a",options="headers,unnumbered"]
|===
5+h| *Information associations*

h|S-127 Role	h|S-127 Association Name h| Associated to h| Type	h| Mult.
|isApplicableTo|InclusionType|Applicability|association|0,*
|theOrganisation|RelatedOrganisation|Authority|association|0,*
|===


include::../instructions/AbstractRxN.adoc[]
* If the complex attribute _rxNCode_ is present at least one of its sub-attributes must be populated.
* If the complex attribute _textContent_ is present at least one of its sub-attributes must be populated.
** If the _textContent_ sub-attribute _information_ is present at least one of its sub-attributes must be populated.
* If the complex attribute _fixedDateRange_ is present at least one of its sub-attributes must be populated.
* If the complex attribute _sourceIndication_ is present at least one of its sub-attributes must be populated.

