[[ftable_Applicability]]
=== Applicability

[cols="a,a,a,a,a,a,a,a",options="headers,unnumbered"]
|===
8+| [underline]#IHO Definition:# Describes the relationship between vessel characteristics and: (i) the applicability of an associated information object or feature to the vessel; or, (ii) the use of a facility, place, or service by the vessel; or, (iii) passage of the vessel through an area.
8+h| [underline]#S-127 Information Type:# Applicability
8+h| [underline]#Super Type:# InformationType
3+h| S-127 Attribute h| S-57 Acronym 2+h| Allowable Encoding Value h| Type h| Multiplicity
            
3+| In Ballast |
2+| |BO | 0,1

3+| Category of Cargo |
2+|1: Bulk +
2: Container +
3: General +
4: Liquid +
5: Passenger +
6: Livestock +
7: Dangerous or Hazardous +
8: Heavy Lift +
10: Dry Bulk Cargo +
11: Liquid Bulk Cargo +
12: Reefer Container Cargo +
13: Ro-Ro Cargo +
14: Project Cargo +
15: Break Bulk Cargo +
 |EN | 0,*

3+| Category Of Dangerous Or Hazardous Cargo |
2+|1: IMDG Code Class 1 Div. 1.1 +
2: IMDG Code Class 1 Div. 1.2 +
3: IMDG Code Class 1 Div. 1.3 +
4: IMDG Code Class 1 Div. 1.4 +
5: IMDG Code Class 1 Div. 1.5 +
6: IMDG Code Class 1 Div. 1.6 +
7: IMDG Code Class 2 Div. 2.1 +
8: IMDG Code Class 2 Div. 2.2 +
9: IMDG Code Class 2 Div. 2.3 +
10: IMDG Code Class 3 +
11: IMDG Code Class 4 Div. 4.1 +
12: IMDG Code Class 4 Div. 4.2 +
13: IMDG Code Class 4 Div. 4.3 +
14: IMDG Code Class 5 Div. 5.1 +
15: IMDG Code Class 5 Div. 5.2 +
16: IMDG Code Class 6 Div. 6.1 +
17: IMDG Code Class 6 Div. 6.2 +
18: IMDG Code Class 7 +
19: IMDG Code Class 8 +
20: IMDG Code Class 9 +
21: Harmful Substances in Packaged Form +
 |EN | 0,*

3+| Category of Vessel |
2+|1: General Cargo Vessel +
2: Container Carrier +
3: Tanker +
4: Bulk Carrier +
5: Passenger Vessel +
6: Roll-On Roll-Off +
7: Refrigerated Cargo Vessel +
8: Fishing Vessel +
9: Service +
10: Warship +
11: Towed or Pushed Composite Unit +
12: Tug and Tow +
13: Light Recreational +
14: Semi-Submersible Offshore Installation +
15: Jack-Up Exploration or Project Installation +
16: Livestock Carrier +
17: Sport Fishing +
 |CL | 0,1

3+| Category of Vessel Registry |
2+|1: Domestic +
2: Foreign +
 |EN | 0,1

3+| Logical Connectives |
2+|1: Logical Conjunction +
2: Logical Disjunction +
 |EN | 0,1

3+| Thickness of Ice Capability |
2+| |IN | 0,1

3+| Vessel Performance |
2+| |TE | 0,1

3+| Destination |
2+| |TE | 0,1

3+| Information | 2+| |  C | 0,*
3+| &nbsp;&nbsp;&nbsp;&nbsp;File Locator |
2+| |(S) TE | 0,1

3+| &nbsp;&nbsp;&nbsp;&nbsp;File Reference |
2+| |(S) TE | 0,1

3+| &nbsp;&nbsp;&nbsp;&nbsp;Headline |
2+| |(S) TE | 0,* (ordered)

3+| &nbsp;&nbsp;&nbsp;&nbsp;Language |
2+| |(S) TE | 0,1

3+| &nbsp;&nbsp;&nbsp;&nbsp;Text |
2+| |(S) TE | 0,1

3+| Vessel Measurements Specification | 2+| |  C | 0,*
3+| &nbsp;&nbsp;&nbsp;&nbsp;Comparison Operator |
2+|1: Greater Than +
2: Greater Than or Equal To +
3: Less Than +
4: Less Than or Equal To +
5: Equal To +
6: Not Equal To +
 |(S) EN | 1,1

3+| &nbsp;&nbsp;&nbsp;&nbsp;Vessels Characteristics |
2+|1: Length Overall +
2: Length at Waterline +
3: Breadth +
4: Draught +
6: Displacement Tonnage +
7: Displacement Tonnage, Light +
8: Displacement Tonnage, Loaded +
9: Deadweight Tonnage +
10: Gross Tonnage +
11: Net Tonnage +
12: Panama Canal/Universal Measurement System Net Tonnage +
13: Suez Canal Net Tonnage +
 |(S) EN | 1,1

3+| &nbsp;&nbsp;&nbsp;&nbsp;Vessels Characteristics Value |
2+| |(S) RE | 1,1

3+| &nbsp;&nbsp;&nbsp;&nbsp;Vessels Characteristics Unit |
2+|1: Metres +
3: Metric Ton +
4: Ton +
5: Short Ton +
6: Gross Ton +
7: Net Ton +
9: Suez Canal Net Tonnage +
 |(S) EN | 1,1

8+h| Inherited Attributes

3+h| S-127 Attribute 3+h| Inherited From h| Type h| Multiplicity
            
3+| Feature Name 3+| InformationType | C | 0,*
3+| Fixed Date Range 3+| InformationType | C | 0,1
3+| Periodic Date Range 3+| InformationType | C | 0,*
3+| Graphic 3+| InformationType | C | 0,*
3+| Source Indication 3+| InformationType | C | 0,*
|===

[cols="a,a,a,a,a",options="headers,unnumbered"]
|===
5+h| *Information associations*

h|S-127 Role	h|S-127 Association Name h| Associated to h| Type	h| Mult.
|theApplicableRxN|InclusionType|AbstractRxN|association|0,*
|===


include::../instructions/Applicability.adoc[]
* If the complex attribute _information_ is present at least one of its sub-attributes must be populated.
* If the complex attribute _fixedDateRange_ is present at least one of its sub-attributes must be populated.
* If the complex attribute _sourceIndication_ is present at least one of its sub-attributes must be populated.

