[[ftable_PilotBoardingPlace]]
=== Pilot Boarding Place

[cols="a,a,a,a,a,a,a,a",options="headers,unnumbered"]
|===
8+| [underline]#IHO Definition:# A location offshore where a pilot may board a vessel in preparation to piloting it through local waters.
8+h| [underline]#S-127 Geo Feature:# PilotBoardingPlace
8+h| [underline]#Super Type:# OrganizationContactArea
8+h| [underline]#Primitives:# point surface
3+| _Real World_ 2+| _Paper Chart Symbol_ 3+| _ECDIS Symbol_
3+h|S-127 Attribute h| S-57 Acronym 2+h| Allowable Encoding Value h| Type h| Multiplicity
3+| Call Sign |
2+| |TE | 0,1

3+| Category of Pilot Boarding Place |
2+|1: Boarding by Pilot-Cruising Vessel +
2: Boarding by Helicopter +
3: Pilot Comes Out from Shore +
 |EN | 0,1

3+| Category of Preference |
2+|1: Primary +
2: Alternate +
 |EN | 0,1

3+| Category of Vessel |
2+|1: General Cargo Vessel +
2: Container Carrier +
3: Tanker +
4: Bulk Carrier +
5: Passenger Vessel +
6: Roll-On Roll-Off +
7: Refrigerated Cargo Vessel +
8: Fishing Vessel +
9: Service +
10: Warship +
11: Towed or Pushed Composite Unit +
12: Tug and Tow +
13: Light Recreational +
14: Semi-Submersible Offshore Installation +
15: Jack-Up Exploration or Project Installation +
16: Livestock Carrier +
17: Sport Fishing +
 |CL | 0,1

3+| Communication Channel |
2+| |TE | 0,*

3+| Destination |
2+| |TE | 0,1

3+| Pilot Movement |
2+|1: Embarkation +
2: Disembarkation +
3: Pilot Change +
 |EN | 0,1

3+| Pilot Vessel |
2+| |TE | 0,1

3+| Status |
2+|1: Permanent +
2: Occasional +
5: Periodic/Intermittent +
6: Reserved +
9: Mandatory +
16: Watched +
17: Unwatched +
28: Buoyed +
 |EN | 0,*

8+h| Inherited Attributes

3+h|S-127Attribute 3+h| Inherited From h| Type h| Multiplicity

3+| Interoperability Identifier 3+| FeatureType | URN | 0,*
3+| Feature Name 3+| FeatureType | C | 0,*
3+| Fixed Date Range 3+| FeatureType | C | 0,1
3+| Periodic Date Range 3+| FeatureType | C | 0,*
3+| Scale Minimum 3+| FeatureType | IN | 0,1
3+| Graphic 3+| FeatureType | C | 0,*
3+| Source Indication 3+| FeatureType | C | 0,*
3+| Text Content 3+| FeatureType | C | 0,*
|===

[cols="a,a,a,a,a",options="headers,unnumbered"]
|===
5+h| *Information associations*

h|S-127 Role	h|S-127 Association Name h| Associated to h| Type	h| Mult.

|theContactDetails|ServiceContact + 
(inherited from OrganizationContactArea) |ContactDetails|association|0,*
|permission|PermissionType + 
(inherited from FeatureType) |Applicability|association|0,*
|theRxN|AssociatedRxN + 
(inherited from FeatureType) |AbstractRxN|association|0,*
|theInformation|AdditionalInformation + 
(inherited from FeatureType) |NauticalInformation|association|0,*
|===


[cols="a,a,a,a,a",options="headers,unnumbered"]
|===
5+h| *Feature associations*

h|S-127 Role	h|S-127 Association Name h| Associated to h| Type	h| Mult.
|theCollection|PilotageDistrictAssociation|PilotageDistrict|aggregation|0,1
|serviceProvider|ServiceProvisionArea|PilotService|association|0,*
|theCartographicText|TextAssociation + 
(inherited from FeatureType) |TextPlacement|association|0,1
|===


include::../instructions/PilotBoardingPlace.adoc[]
* If the complex attribute _fixedDateRange_ is present at least one of its sub-attributes must be populated.
* If the complex attribute _sourceIndication_ is present at least one of its sub-attributes must be populated.
* If the complex attribute _textContent_ is present at least one of its sub-attributes must be populated.
** If the _textContent_ sub-attribute _information_ is present at least one of its sub-attributes must be populated.

