[[ftable_QualityOfNonBathymetricData]]
=== Quality of Non-Bathymetric Data

[cols="a,a,a,a,a,a,a,a",options="headers,unnumbered"]
|===
8+| [underline]#IHO Definition:# An area within which a uniform assessment of the quality of the non-bathymetric data exists.
8+h| [underline]#S-127 Geo Feature:# QualityOfNonBathymetricData
8+h| [underline]#Super Type:# 
8+h| [underline]#Primitives:# surface
3+| _Real World_ 2+| _Paper Chart Symbol_ 3+| _ECDIS Symbol_
3+h|S-127 Attribute h| S-57 Acronym 2+h| Allowable Encoding Value h| Type h| Multiplicity
3+| Category of Temporal Variation |
2+|1: Extreme Event +
4: Likely to Change +
5: Unlikely to Change +
6: Unassessed +
 |EN | 0,1

3+| Horizontal Distance Uncertainty |
2+| |RE | 0,1

3+| Orientation Uncertainty |
2+| |RE | 0,1

3+| Horizontal Position Uncertainty | 2+| |  C | 0,1
3+| &nbsp;&nbsp;&nbsp;&nbsp;Uncertainty Fixed |
2+| |(S) RE | 1,1

3+| &nbsp;&nbsp;&nbsp;&nbsp;Uncertainty Variable Factor |
2+| |(S) RE | 0,1

3+| Interoperability Identifier |
2+| |URN | 0,*

3+| Source Indication | 2+| |  C | 0,1
3+| &nbsp;&nbsp;&nbsp;&nbsp;Category of Authority |
2+|2: Border Control +
3: Police +
4: Port +
5: Immigration +
6: Health +
7: Coast Guard +
8: Agricultural +
9: Military +
10: Private Company +
11: Maritime Police +
12: Environmental +
13: Fishery +
14: Finance +
15: Maritime +
16: Customs +
 |(S) EN | 0,1

3+| &nbsp;&nbsp;&nbsp;&nbsp;Country Name |
2+| |(S) TE | 0,1

3+| &nbsp;&nbsp;&nbsp;&nbsp;Source |
2+| |(S) TE | 0,1

3+| &nbsp;&nbsp;&nbsp;&nbsp;Source Type |
2+|1: Law or Regulation +
2: Official Publication +
7: Mariner Report, Confirmed +
8: Mariner Report, Not Confirmed +
9: Industry Publications and Reports +
10: Remotely Sensed Images +
11: Photographs +
12: Products Issued by HO Services +
13: News Media +
14: Traffic Data +
 |(S) EN | 0,1

3+| &nbsp;&nbsp;&nbsp;&nbsp;Reported Date |
2+| |(S) TD | 0,1

3+| &nbsp;&nbsp;&nbsp;&nbsp;Feature Name | 2+| | (S)  C | 0,*
3+| Survey Date Range | 2+| |  C | 0,1
3+| &nbsp;&nbsp;&nbsp;&nbsp;Date Start |
2+| |(S) TD | 0,1

3+| &nbsp;&nbsp;&nbsp;&nbsp;Date End |
2+| |(S) TD | 1,1

3+| Information | 2+| |  C | 0,*
3+| &nbsp;&nbsp;&nbsp;&nbsp;File Locator |
2+| |(S) TE | 0,1

3+| &nbsp;&nbsp;&nbsp;&nbsp;File Reference |
2+| |(S) TE | 0,1

3+| &nbsp;&nbsp;&nbsp;&nbsp;Headline |
2+| |(S) TE | 0,* (ordered)

3+| &nbsp;&nbsp;&nbsp;&nbsp;Language |
2+| |(S) TE | 0,1

3+| &nbsp;&nbsp;&nbsp;&nbsp;Text |
2+| |(S) TE | 0,1

8+h| Inherited Attributes

3+h|S-127Attribute 3+h| Inherited From h| Type h| Multiplicity

8+h| No inherited attributes
|===

[cols="a,a,a,a,a",options="headers,unnumbered"]
|===
5+h| *Information associations*

h|S-127 Role	h|S-127 Association Name h| Associated to h| Type	h| Mult.

|===


[cols="a,a,a,a,a",options="headers,unnumbered"]
|===
5+h| *Feature associations*

h|S-127 Role	h|S-127 Association Name h| Associated to h| Type	h| Mult.
|===


include::../instructions/QualityOfNonBathymetricData.adoc[]
* If the complex attribute _sourceIndication_ is present at least one of its sub-attributes must be populated.
* If the complex attribute _information_ is present at least one of its sub-attributes must be populated.

