[[ftable_ServiceHours]]
=== Service Hours

[cols="a,a,a,a,a,a,a,a",options="headers,unnumbered"]
|===
8+| [underline]#IHO Definition:# The time when a service is available and known exceptions.
8+h| [underline]#S-127 Information Type:# ServiceHours (Abstract type)
8+h| [underline]#Super Type:# InformationType
3+h| S-127 Attribute h| S-57 Acronym 2+h| Allowable Encoding Value h| Type h| Multiplicity
            
3+| Schedule by Day of Week | 2+| |  C | 1,*
3+| &nbsp;&nbsp;&nbsp;&nbsp;Category of Schedule |
2+|1: Normal Operation +
2: Closure +
3: Unmanned Operation +
 |(S) EN | 0,1

3+| &nbsp;&nbsp;&nbsp;&nbsp;Text |
2+| |(S) TE | 0,1

3+| &nbsp;&nbsp;&nbsp;&nbsp;Time Intervals by Day of Week | 2+| | (S)  C | 1,*
3+| Information | 2+| |  C | 0,*
3+| &nbsp;&nbsp;&nbsp;&nbsp;File Locator |
2+| |(S) TE | 0,1

3+| &nbsp;&nbsp;&nbsp;&nbsp;File Reference |
2+| |(S) TE | 0,1

3+| &nbsp;&nbsp;&nbsp;&nbsp;Headline |
2+| |(S) TE | 0,* (ordered)

3+| &nbsp;&nbsp;&nbsp;&nbsp;Language |
2+| |(S) TE | 0,1

3+| &nbsp;&nbsp;&nbsp;&nbsp;Text |
2+| |(S) TE | 0,1

8+h| Inherited Attributes

3+h| S-127 Attribute 3+h| Inherited From h| Type h| Multiplicity
            
3+| Feature Name 3+| InformationType | C | 0,*
3+| Fixed Date Range 3+| InformationType | C | 0,1
3+| Periodic Date Range 3+| InformationType | C | 0,*
3+| Graphic 3+| InformationType | C | 0,*
3+| Source Indication 3+| InformationType | C | 0,*
|===

[cols="a,a,a,a,a",options="headers,unnumbered"]
|===
5+h| *Information associations*

h|S-127 Role	h|S-127 Association Name h| Associated to h| Type	h| Mult.
|partialWorkingDay|ExceptionalWorkday|NonStandardWorkingDay|association|0,*
|theAuthority_srvHrs|AuthorityHours|Authority|association|0,*
|===


include::../instructions/ServiceHours.adoc[]
* If the complex attribute _information_ is present at least one of its sub-attributes must be populated.
* If the complex attribute _fixedDateRange_ is present at least one of its sub-attributes must be populated.
* If the complex attribute _sourceIndication_ is present at least one of its sub-attributes must be populated.

