[[ftable_ShipReport]]
=== Ship Report

[cols="a,a,a,a,a,a,a,a",options="headers,unnumbered"]
|===
8+| [underline]#IHO Definition:# Description of how a ship should report to a maritime authority, including when to report, what to report and whether the format conforms to the IMO standard.
8+h| [underline]#S-127 Information Type:# ShipReport
8+h| [underline]#Super Type:# InformationType
3+h| S-127 Attribute h| S-57 Acronym 2+h| Allowable Encoding Value h| Type h| Multiplicity
            
3+| Category of Ship Report |
2+|1: Sailing Plan +
2: Position Report +
3: Deviation Report +
4: Final Report +
5: Dangerous Goods Report +
6: Harmful Substances Report +
7: Marine Pollutants Report +
8: Any Other Report +
 |EN | 1,*

3+| IMO Format for Reporting |
2+| |BO | 1,1

3+| SRS Format Code |
2+|1: IMO Ship Reporting Format A +
2: IMO Ship Reporting Format B +
3: IMO Ship Reporting Format C +
4: IMO Ship Reporting Format D +
5: IMO Ship Reporting Format E +
6: IMO Ship Reporting Format F +
7: IMO Ship Reporting Format G +
8: IMO Ship Reporting Format H +
9: IMO Ship Reporting Format I +
10: IMO Ship Reporting Format J +
11: IMO Ship Reporting Format K +
12: IMO Ship Reporting Format L +
13: IMO Ship Reporting Format M +
14: IMO Ship Reporting Format N +
15: IMO Ship Reporting Format O +
16: IMO Ship Reporting Format P +
17: IMO Ship Reporting Format Q +
18: IMO Ship Reporting Format R +
19: IMO Ship Reporting Format S +
20: IMO Ship Reporting Format T +
21: IMO Ship Reporting Format U +
22: IMO Ship Reporting Format V +
23: IMO Ship Reporting Format W +
24: IMO Ship Reporting Format X +
25: IMO Ship Reporting Format Y +
26: IMO Ship Reporting Format Z +
 |EN | 0,* (ordered)

3+| Notice Time | 2+| |  C | 1,*
3+| &nbsp;&nbsp;&nbsp;&nbsp;Notice Time Hours |
2+| |(S) RE | 0,* (ordered)

3+| &nbsp;&nbsp;&nbsp;&nbsp;Notice Time Text |
2+| |(S) TE | 0,1

3+| &nbsp;&nbsp;&nbsp;&nbsp;Operation |
2+|1: Largest Value +
2: Smallest Value +
 |(S) EN | 0,1

3+| Text Content | 2+| |  C | 0,1
3+| &nbsp;&nbsp;&nbsp;&nbsp;Category of Text |
2+|1: Abstract or Summary +
2: Extract +
3: Full Text +
 |(S) EN | 0,1

3+| &nbsp;&nbsp;&nbsp;&nbsp;Information | 2+| | (S)  C | 0,*
3+| &nbsp;&nbsp;&nbsp;&nbsp;Online Resource | 2+| | (S)  C | 0,1
3+| &nbsp;&nbsp;&nbsp;&nbsp;Source Indication | 2+| | (S)  C | 0,*
8+h| Inherited Attributes

3+h| S-127 Attribute 3+h| Inherited From h| Type h| Multiplicity
            
3+| Feature Name 3+| InformationType | C | 0,*
3+| Fixed Date Range 3+| InformationType | C | 0,1
3+| Periodic Date Range 3+| InformationType | C | 0,*
3+| Graphic 3+| InformationType | C | 0,*
3+| Source Indication 3+| InformationType | C | 0,*
|===

[cols="a,a,a,a,a",options="headers,unnumbered"]
|===
5+h| *Information associations*

h|S-127 Role	h|S-127 Association Name h| Associated to h| Type	h| Mult.
|mustBeFiledBy|ReportingRequirement|Applicability|association|0,*
|reportTo|ReportingAuthority|Authority|association|0,*
|===


include::../instructions/ShipReport.adoc[]
* If the complex attribute _noticeTime_ is present at least one of its sub-attributes must be populated.
* If the complex attribute _textContent_ is present at least one of its sub-attributes must be populated.
** If the _textContent_ sub-attribute _information_ is present at least one of its sub-attributes must be populated.
* If the complex attribute _fixedDateRange_ is present at least one of its sub-attributes must be populated.
* If the complex attribute _sourceIndication_ is present at least one of its sub-attributes must be populated.

