==== General

For a pilot boarding place, the pilot vessel may either cruise in the area or come out on request. Off some large ports pilots on outgoing ships may be disembarked at a different location. Pilots may board from a helicopter; it is then less important for a ship to reach the exact position of the boarding place but an approximate position should still be encoded. Some pilot stations are used solely for long-distance (deep-sea) pilots. Pilots may be in constant attendance, in regular attendance at certain limited times, or available by previous arrangement only. The primary purpose of encoded pilotage information is to show the position of the facility. Because of the many variations in the service provided, the main source of information on pilotage must be in an associated publication or product.

If it is required to encode a pilot boarding place, it must be done using the feature *PilotBoardingPlace*.

==== Remarks

* If it is required to encode the ship to shore or shore to ship contact information separately from piloting contacts, it must be done using the information class *ContactDetails* (see clause <<ftable_ContactDetails,droploc%>>). The *ContactDetails* must be associated to the *PilotBoardingPlace* feature using the association *AdditionalInformation* and must indicate that is is for ship-to-shore communications in a _contactInstructions_ or _information.headline_ attribute.
* If it is required to encode the area in which pilotage regulations apply, it should be done using the feature *PilotageDistrict* (see clause <<ftable_PilotageDistrict,droploc%>>). The relationship between the pilotage district and any associated pilot boarding places should be encoded using the feature association *PilotageDistrictAssociation* (see clause <<fa_PilotageDistrictAssociation,droploc%>>).
* If a pilot boarding place has one or more communication channels designated for use in connection with pilotage activities at that particular boarding place, the channel(s) should be encoded using the _communicationChannel_ attribute. Such a situation may arise if there are multiple boarding places in a pilotage district.
